# This rule is not used by the project dream-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the devops.devopsengineer.ing.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dream-operator
    app.kubernetes.io/managed-by: kustomize
  name: learn-editor-role
rules:
- apiGroups:
  - devops.devopsengineer.ing
  resources:
  - learns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.devopsengineer.ing
  resources:
  - learns/status
  verbs:
  - get
