# This rule is not used by the project dream-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over devops.devopsengineer.ing.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dream-operator
    app.kubernetes.io/managed-by: kustomize
  name: learn-admin-role
rules:
- apiGroups:
  - devops.devopsengineer.ing
  resources:
  - learns
  verbs:
  - '*'
- apiGroups:
  - devops.devopsengineer.ing
  resources:
  - learns/status
  verbs:
  - get
